const avatarsAnimal = [
  "Seahorse.svg",
  "Shark.svg",
  "Sheep.svg",
  "Snail.svg",
  "Spider.svg",
  "Starfish.svg",
  "Stork.svg",
  "Tentacles.svg",
  "Turtle.svg",
  "Unicorn.svg",
  "Wasp.svg",
  "Whale.svg",
  "Wolf.svg",
  "Ant.svg",
  "Aquarium.svg",
  "Badger.svg",
  "Bat Face.svg",
  "Bear.svg",
  "Beaver.svg",
  "Bee.svg",
  "Bird.svg",
  "Bug.svg",
  "Bull.svg",
  "Bumblebee.svg",
  "Butterfly.svg",
  "Cat Footprint.svg",
  "Cat.svg",
  "Caterpillar.svg",
  "Chicken.svg",
  "Clown Fish.svg",
  "Corgi.svg",
  "Cow.svg",
  "Crab.svg",
  "Deer.svg",
  "Dinosaur.svg",
  "Dog Park.svg",
  "Dog.svg",
  "Dolphin.svg",
  "Dragonfly.svg",
  "Duck.svg",
  "Elephant.svg",
  "Falcon.svg",
  "Fish Food.svg",
  "Fish.svg",
  "Fly.svg",
  "Frog.svg",
  "Giraffe.svg",
  "Gorilla.svg",
  "Grasshopper.svg",
  "Hornet Hive.svg",
  "Hornet.svg",
  "Horse.svg",
  "Hummingbird.svg",
  "Icons8 Logo.svg",
  "Insect.svg",
  "Kangaroo.svg",
  "Kiwi Bird.svg",
  "Ladybird.svg",
  "Leopard.svg",
  "Lion.svg",
  "Llama.svg",
  "Mite.svg",
  "Mosquito.svg",
  "Octopus.svg",
  "Panda.svg",
  "Pig With Lipstick.svg",
  "Pig.svg",
  "Prawn.svg",
  "Puffin Bird.svg",
  "Rabbit.svg",
  "Rhinoceros.svg"
];

export const selectRandomAvatar = () => {
  const index = Math.floor(Math.random() * 101);
  const userRandomAvatar = avatarsAnimal[index];
  return userRandomAvatar;
};
